name: go_router_plus
description: Building blocks screens, access control and refresh notifiers base on Go Router.
version: 4.1.1
repository: https://github.com/vuongxuongminh/go_router_plus

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ">=6.5.2 <8.0.0"
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  very_good_analysis: ^4.0.0
