name: go_router_plus
description: Building blocks screens, access control and refresh notifiers base on Go Router.
version: 2.0.0
repository: https://github.com/vuongxuongminh/go_router_plus

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ">=5.0.1 <7.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  very_good_analysis: ^3.1.0
